### ISSUE TITLE
Modify Swagger UI Title, Description and Version.

### ISSUE THREAD

**Issue by shoeb22387** [yuka1984/azure-functions-extensions-swashbuckle#12]
Hi,

I am using this package to display Swagger UI but I don't want predefined Title, Description and Version on UI. 
Can you please suggest, how can I modify below information in my Azure Function-2 application?

Kindly see attached screen shots. I have also attached one screen-shot highlighting the configuration I have done.

![Swag1](https://user-images.githubusercontent.com/55238037/64780557-575fc300-d57e-11e9-90eb-416311683d9d.png)
![Swag2](https://user-images.githubusercontent.com/55238037/64780563-5dee3a80-d57e-11e9-86d8-d8cc4ea09800.png)

**Comment by rafaelfbs** [comment]
See #10
