### ISSUE TITLE
Invalid OperationIds Error

### ISSUE THREAD

**Issue by stephanruhland** [yuka1984/azure-functions-extensions-swashbuckle#13]
Hi,
i ran into an invalid swagger documentation with the following setup:
Installed nuget in version 1.4.1 and specified multiple methods (get and post) in a http triggered function. I added a screenshot of the function:
![image](https://user-images.githubusercontent.com/1325150/65876120-dd567900-e388-11e9-86c0-25f785de6855.png)

The generated definition now contains two operation ids with the same name ("Run"):
_[…]
/api/test:
    get:
      tags:
        - TestFunction
      operationId: **Run**
      consumes: []
      produces: []
      parameters: []
      responses:
        '200':
          description: Success
    post:
      tags:
        - TestFunction
      operationId: **Run**
      consumes: []
      produces: []
      parameters: []
      responses:
        '200':
          description: Success
[…]_

Swagger Online Validator Error Message:
_{"messages":["attribute paths.'/api/test'(get).operationId is repeated","attribute paths.'/api/test'(post).operationId is repeated"]}_

Swagger Editor Error Message:
_Semantic error at paths./api/test.get.operationId
Operations must have unique operationIds.
Jump to line 28
Semantic error at paths./api/test.post.operationId
Operations must have unique operationIds.
Jump to line 38_

Kind Regards

**Comment by yuka1984** [comment]
Hi @stephanruhland .
Thank you.
