### ISSUE TITLE
Group functions in SwaggerUI

### ISSUE THREAD

**Issue by stephanruhland** [yuka1984/azure-functions-extensions-swashbuckle#23]
Hi yuka1984,
in my current function implementations every method has its own headline in the ui.
Is it possible to group the function methods e.g. by class or by a custom name?
Current:
![image](https://user-images.githubusercontent.com/1325150/70847120-c809ca80-1e60-11ea-9c20-6cf3d0c2379c.png)
Idea (Tags Attribute?):
![image](https://user-images.githubusercontent.com/1325150/70847122-cf30d880-1e60-11ea-94cb-2fd65e11e5ea.png)

Kind regards

**Comment by WolfyUK** [comment]
Try applying the `ApiExplorerSettings` attribute to your Function methods, e.g.:

```
[ApiExplorerSettings(GroupName = "MyGroup")]
```

**Comment by stephanruhland** [comment]
Thank you :)
