### ISSUE TITLE
How to describe url query parameters

### ISSUE THREAD

**Issue by kjartanvalur** [yuka1984/azure-functions-extensions-swashbuckle#24]
For example if the GetItems had two url query parameters "code" and "category"
Is it possible to set this up so the query parameters can be visible in swagger ui?

Thanks

**Comment by TiagoCastilhos** [comment]
You can use "QueryStringParamater" attribute, it worked for me

**Comment by TiagoCastilhos** [comment]
eg: [QueryStringParamater("name", "Customer name", DataType = typeof(string))].
If you don't set DataType parameter, it will give an error.

**Comment by kjartanvalur** [comment]
@TiagoCastilhos 
Thanks
