### ISSUE TITLE
Azure API Management

### ISSUE THREAD

**Issue by bbakermmc** [yuka1984/azure-functions-extensions-swashbuckle#33]
Does anyone use this with Azure API Management?
It seems like their "portal" screen doesnt render "objects" defined in schemes.
EX:
![image](https://user-images.githubusercontent.com/30090055/75911309-5f0d6f80-5e1d-11ea-93b2-c487ff1e3221.png)

vs

![image](https://user-images.githubusercontent.com/30090055/75911364-751b3000-5e1d-11ea-9cf7-464c07debf7d.png)

**Comment by justin-vanwinkle** [comment]
Did you create the APIM API by givin APIM your Swagger json or via some other method?

**Comment by bbakermmc** [comment]
I just pointed to the json URL of the function app just like in the swagger ui.

**Comment by bbakermmc** [comment]
Maybe this helps? 
https://docs.microsoft.com/en-us/azure/api-management/api-management-api-import-restrictions

**Comment by LockTar** [comment]
I don't think this has anything to do with this package. We are writing the open api spec for a new project manually (yaml). We came a cross this problem as well. Arrays of objects are ignored as well. I think this is a bug in api management...

**Comment by bbakermmc** [comment]
@LockTar Yeah I'm not sure where the error is currently lol, it could be API Mgnt wants a diff format.  I posted the issue on their github also.  Was just wondering if anyone had a quick answer where I could just do a quick find replace or something, or if we knew what the standard was have an option to output in that format :)

https://github.com/Azure/api-management-developer-portal/issues/522

**Comment by bbakermmc** [comment]
Looks like they have a bug and know how to fix.  Yay.

https://github.com/Azure/api-management-developer-portal/issues/522#issuecomment-595452958

> Looks like we're missing allOf case when rendering the documentation.
