### ISSUE TITLE
Swagger security flaw

### ISSUE THREAD

**Issue by nirnaybansal** [yuka1984/azure-functions-extensions-swashbuckle#4]
AuthorizationLevel defined as Function. i.e. The caller have to specify key in the request otherwise caller will receive a 401 Unauthorized..

But how come when I click "Execute" in Swagger UI, it is successfully calling the function.
Isn't this is a security flaw? i.e. if I host my Function app with this Swagger, anyone in could potentially call it successfully?

**Comment by yuka1984** [comment]
Hi @nirnaybansal .
If you use version 1.3.1 package and AuthorizationLevel is Function.
You can input code property on swagger ui.
Please set functions key to this property.

![スクリーンショット 2019-07-08 20 26 37](https://user-images.githubusercontent.com/13382333/60806878-226e7300-a1bf-11e9-8f66-9ac7025ca887.png)
